### ISSUE TITLE
NTV in steep gradient region vE^2

### ISSUE THREAD

**Issue by krystophny** [itpplasma/NEO-RT#3]

**Comment by krystophny** [comment]
*Automated triage pass (Claude), grounded in the repository at `9719012`. Verify before acting.*

The issue body is empty, so the first job is to pin down what "vE^2" means here and whether the gap is still open. It is: NEO-RT today keeps the E×B drift only to **first** order in `v_E` (as a rigid toroidal precession `Om_tE`) and drops every `O(v_E^2/v_th^2)` term from the orbit dynamics and from the background distribution. In the steep-gradient region those terms are not small. Spec below.

Related but distinct: itpplasma/SIMPLE#71 ("add electric field including vE^2 term", opened the same minute by the same author) is the sibling task for the full-orbit-width tracer; itpplasma/NEO-RT#50 and itpplasma/rabe#37 touch the same pedestal/`E_r` physics from other angles. This issue is not a duplicate of any of them.

## Purpose

NEO-RT is applied to pedestal NTV (see the `rmp_torque` AUG/MAST-U cases, itpplasma/rmp_torque#4, #5). In an H-mode pedestal `E_r` reaches several tens of kV/m over a few cm, so `v_E/v_th = M_t` is 0.1–0.5 and `M_t^2` is a 1–25 % effect — comparable to or larger than the nonlinear attenuation correction the code already bothers to model (`src/nonlin.f90`). The `O(M_t)` physics is complete: for `Phi = Phi(psi)` the E×B drift is a rigid toroidal rotation, which is exactly what `Om_tE` in `src/freq.f90:293` encodes. What is missing is everything quadratic in `v_E`: the centrifugal/electrostatic modification of the parallel (mirror) dynamics, the resulting shift of the trapped–passing boundary and of `omega_b`, and the rotating-frame (canonical) Maxwellian with its extra thermodynamic-force term. Without them, NEO-RT's trapped fraction and resonance line in the pedestal are those of a non-rotating plasma.

## Current state

**1. Parallel velocity is a pure magnetic mirror.** `src/orbit.f90:125-133`:

```fortran
    pure function vpar(v, eta, bmod)
        !   parallel velocity
        real(dp) :: vpar
        real(dp), intent(in) :: v, eta, bmod
        vpar = v * sqrt(1.0_dp - eta * bmod)
```

No electrostatic or centrifugal potential. `rg -n 'Phi|phi_elec|potential' src/*.f90` returns nothing for an electrostatic potential anywhere in `src/` — the only `Phi` in the NEO-RT tree is inside `POTATO/` (see below).

**2. The poloidal equation of motion carries only `dB/dtheta`.** `src/orbit.f90:263-270`:

```fortran
    pure subroutine poloidal_velocity(v, eta, bmod, hthctr, hderth, v_par, ydot)
        ...
        ydot(1) = v_par * hthctr ! theta
        ydot(2) = -v**2 * eta / 2.0_dp * hthctr * hderth * bmod ! v_par
```

**3. The trapped–passing boundary is purely geometric and energy-independent.** `src/magfie.f90:61-62`:

```fortran
        etatp = 1.0_dp / Bmax
        etadt = 1.0_dp / Bmin
```

consumed by `neort::set_to_trapped_region` / `set_to_passing_region` (`src/neort.f90:33-49`).

**4. The frequency splines assume `taub * v` is energy-independent.** `src/freq.f90:84` and `:183` build the splines at a single speed `v = vth`, and `Om_th` rescales linearly, `src/freq.f90:338-339`:

```fortran
        Omth = sign_vpar * splineval(1) * v
        dOmthdv = sign_vpar * splineval(1)
```

That scaling is exact only while `v_par/v` is a function of `eta` and `theta` alone. Any potential term breaks it (see BDD scenario 3) — this is the structural cost of the change.

**5. The thermodynamic force is the local-Maxwellian one.** `src/profiles.f90:209-216`:

```fortran
        A1 = dni1ds / ni1 - qi / (Ti1 * ev) * sign_theta * psi_pr / (q * c) * Om_tE - 3.0_dp / &
             2.0_dp * dTi1ds / Ti1
        A2 = dTi1ds / Ti1
```

i.e. `A1 = n'/n - e Phi'/T - (3/2) T'/T`, matching eq. at `doc/driftorbit.lyx:1183`. The velocity weight in `src/transport.f90:48-55` is the plain `ux**3 * exp(-ux**2)`.

**6. The theory notes state the assumption explicitly.** `doc/driftorbit.lyx:474` writes `v_par = sigma sqrt(2/m (H - e Phi(p_phi) - J_perp omega_c(theta, p_phi)))` — `Phi` a function of `p_phi` only, so in the thin-orbit limit it is constant along the orbit and drops out of the parallel dynamics entirely.

**7. `R(theta)` is not currently available for the test equilibrium.** The centrifugal term needs the major radius on the flux surface. `do_magfie_standalone::booz_to_cyl` (`src/do_magfie_standalone.f90:471`) does `if (inp_swi /= 9) error stop`, yet the `r/[m]` harmonics are present for `inp_swi = 8` too (`ncol2 = 4` at `src/do_magfie_standalone.f90:99`; column 3 of the mode block in `examples/circ.bc`, which is where `R0 = modes0(1, 1, 3)*100` comes from, `src/do_magfie_standalone.f90:468`).

**8. POTATO already has this physics** — `POTATO/SRC/velo.f90:12` calls `phielec_of_psi`, and the resonant-torque integrand carries `phi_elec` and `dPhi_dpsi` (`POTATO/SRC/resonant_int.f90:300-313`). POTATO is finite-orbit-width, so it also captures orbit squeezing, which a thin-orbit code structurally cannot. That makes POTATO the natural cross-check (see itpplasma/NEO-RT#51) and the natural home for the FOW part.

## Reproduction / evidence

This is a missing-physics issue, so the demonstration is that the orbit topology is currently rotation-independent, followed by an analytic acceptance check.

**A. Show the gap (works today, at `9719012`):**

```bash
cd /path/to/NEO-RT && make                # cmake+ninja, per Makefile
mkdir -p /tmp/vE2 && cd /tmp/vE2
for f in driftorbit.in in_file neo.in plasma.in profile.in; do
    ln -sf /path/to/NEO-RT/examples/base/$f .
done
sed -i 's/M_t = 0.036/M_t = 0.36/' driftorbit.in   # 10x rotation
/path/to/NEO-RT/build/neo_rt.x driftorbit
grep -iE 'etatp|etadt|B0|eps' driftorbit_magfie_param.out
```

Observed: the printed `etatp`, `etadt` and the trapped-fraction-defining `eps` are bit-identical to the `M_t = 0.036` run (they come from `Bmin`/`Bmax` alone, `src/magfie.f90:61-62`). Expected with the `vE^2` term: at `M_t = 0.36` the effective mirror ratio grows, `etatp` drops by `~2 * eps * M_eff^2` (see below), and the trapped-class contribution `D11t` in `driftorbit.out` changes by a percent-level amount beyond the pure resonance shift.

**B. Analytic acceptance check for the implementation.** For a single ion species with adiabatic electrons and rigid toroidal rotation `Omega = v_th M_t / R0`, parallel force balance plus quasineutrality give the ion effective potential on the flux surface

```
e Phi(theta) - (m_i/2) Omega^2 R^2(theta) = -(m_i/2) Omega^2 R^2(theta) * T_i/(T_i + Z T_e) + const
```

Define the dimensionless in-surface potential `Uhat(theta) = (2/(m_i v_th^2)) * [e Phi - (m_i/2) Omega^2 R^2]`, referenced to `theta = 0`. For the circular equilibrium in `examples/circ.bc`, `R = R0 (1 + eps cos theta)` and `B = B0 (1 - eps cos theta)`, hence

```
Uhat(theta) = -2 eps M_eff^2 cos(theta),   M_eff^2 = M_t^2 * T_i/(T_i + Z T_e)
```

and, with `vpar^2/v^2 = 1 - eta B - Uhat/u^2` (`u = v/v_th`), the trapped–passing boundary becomes

```
eta_tp(u) = 1 / max_theta [ B(theta) / (1 - Uhat(theta)/u^2) ]
          = 1 / [ B0 (1 + eps_eff) ],   eps_eff = eps (1 + 2 M_eff^2/u^2)  + O(eps^2)
```

So at `u = 1` the leading-order prediction is `(eta_tp(M) - eta_tp(0)) / eta_tp(0) = -2 eps M_eff^2` to `O(eps, M^4)`. That is the number a unit test should hit. With `examples/base` (`s = 0.5`, `eps` as printed in `driftorbit_magfie_param.out`, roughly 0.2 for `circ.bc`, `T_i ≈ T_e` so `M_eff^2 ≈ M_t^2/2`) and `M_t = 0.36` this is a shift of order 1–3 % — small but unambiguous and analytically known.

## Behaviour (BDD)

```gherkin
Scenario: vE^2 disabled reproduces the current code bit-for-bit
  Given examples/base/driftorbit.in with the new key rotation_energy = .false. (default)
  When build/neo_rt.x driftorbit is run in examples/base
  Then driftorbit.out, driftorbit_torque.out and the HDF5 entries checked by
       test/golden_record/test_golden_record.py match test/golden_record/golden.h5
       to the existing golden tolerances, with no regeneration of golden.h5

Scenario: centrifugal well shifts the trapped-passing boundary as predicted
  Given the circular Boozer field examples/circ.bc at s = 0.5, inp_swi = 8
    And rotation_energy = .true., rotation_closure = 'quasineutral', M_t = 0.36
  When test/test_rotation_potential.x evaluates eta_tp(u = 1) via neort_potential::eta_bounds
  Then eta_tp differs from 1/Bmax by -2*eps*M_t^2*Ti/(Ti+Te) with relative error < 5e-2
    And eta_tp(u) -> 1/Bmax as u -> infinity with relative error < 1e-3 at u = 20

Scenario: bounce time acquires the energy dependence the potential implies
  Given rotation_energy = .true., M_t = 0.36, eta = 0.5*(etatp + etadt)
  When neort_orbit::bounce_time is called at u = 0.5 and u = 2.0
  Then taub*v is NOT equal between the two calls (relative difference > 1e-3)
    And with rotation_energy = .false. taub*v agrees between them to < 1e-8,
        confirming the existing eta-only spline is only valid in that limit

Scenario: torque changes only at O(M_t^2)
  Given examples/base with comptorque = .true. and M_t = 0.036
  When neo_rt.x is run with rotation_energy = .false. and then .true.
  Then the total torque density in driftorbit_torque.out changes by less than 1 %
    And repeating with M_t = 0.36 changes it by more than 5 %

Scenario: unsupported field input fails loudly instead of silently dropping the term
  Given rotation_energy = .true. and a Boozer input whose reader cannot supply R(theta)
  When neort_lib::neort_init runs
  Then the run stops with an error naming rotation_energy and the unsupported inp_swi,
       and does not fall back to Uhat = 0
```

## Implementation plan

Split this into three PRs; PR 1 and PR 2 are the deliverable, PR 3 is validation.

**PR 1 — potential model and orbit dynamics**

1. `src/do_magfie_standalone.f90` — generalise `booz_to_cyl` (line 471) to `inp_swi == 8` by using only the cosine harmonics (`rmnc`, `zmnc`; the sine arrays stay zero) and remove the blanket `error stop`; keep the stop for `inp_swi == 10` until the chartmap path exposes `R`. Add a public `subroutine get_R_at_theta(theta, R, dRdtheta)` so callers do not need the full cylindrical map.
2. **New file** `src/rotation_potential.f90`, module `neort_rotation_potential`, with derived type `rotation_potential_t` holding `enabled`, `closure` (`'none' | 'centrifugal' | 'quasineutral'`), `M_eff2`, `R0`, and splined `Uhat`/`dUhat_dtheta` on a `theta` grid built once per flux surface. Public procedures: `init_rotation_potential(M_t, Ti1, Te, Z1, R0)`, `pure function Uhat(theta)`, `pure function dUhat_dtheta(theta)`, and `subroutine eta_bounds(u, eta_tp, eta_dt)` implementing `eta_tp(u) = 1/max_theta[B/(1 - Uhat/u^2)]` by direct sampling on the same `theta` grid plus a golden-section refinement. Guard everything so `enabled = .false.` returns `Uhat = 0` and the existing `1/Bmax`, `1/Bmin`.
3. `src/orbit.f90` — change `vpar` (line 125) to `vpar(v, eta, bmod, theta)` returning `v*sqrt(1 - eta*bmod - Uhat(theta)*(vth/v)**2)`, and add the potential force to `poloidal_velocity` (line 263): `ydot(2) = ydot(2) - 0.5_dp*vth**2*hthctr*dUhat_dtheta(theta)`. `poloidal_velocity` must gain `theta` as an argument; update its two call sites (`src/orbit.f90:260` and `src/transport.f90:163`).
4. `src/magfie.f90` — keep `etatp`/`etadt` (lines 61-62) as the `Uhat = 0` values, and add `etatp_of_u`/`etadt_of_u` wrappers delegating to `eta_bounds`.
5. `src/neort.f90` — `set_to_trapped_region` / `set_to_passing_region` (lines 33-49) take `u` and call the wrappers; `neort_transport::compute_transport_integral` (`src/transport.f90:72`) recomputes `etamin`/`etamax` inside the `ku` loop instead of once outside.
6. `src/config.f90` — add `rotation_energy` (logical, default `.false.`) and `rotation_closure` (character, default `'quasineutral'`) to the `params` namelist (line 82) and to `config_t` in `src/datatypes.f90`; wire them in `read_and_set_config` and `set_config`.
7. `src/lib.f90` — call `init_rotation_potential` from `neort_setup_at_s`, after `init_plasma_at_s`/`init_profile_at_s` (which set `M_t`, `Ti1`, `Te`) and before `init_flux_surface_average`.
8. `CMakeLists.txt` — add `src/rotation_potential.f90` to the `neo_rt` source list.
9. **New test** `test/test_rotation_potential.f90` covering BDD scenarios 2 and 3; register it in `test/CMakeLists.txt` with `add_test(NAME test_rotation_potential ... WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/examples/base)`.
10. `doc/running.md` (namelist table, around line 48) and `doc/library.md` (`config_t` listing, line 162) — document both new keys and state the `M_t^2` ordering.

**PR 2 — energy-dependent frequencies and the rotating-frame Maxwellian**

11. `src/freq.f90` — the single-speed splines at lines 84 and 183 and the linear rescaling at lines 338-339 are only valid for `Uhat = 0`. When `rotation_energy` is on, either (a) extend `Omth_spl_coeff` to a 2-D spline in `(log u, eta)` built on a modest `u` grid (8–16 knots over `u ∈ [0.2, 5]`), or (b) bypass the spline and call `bounce_time`/`bounce_fast` directly. Recommend (b) first for correctness, then (a) for speed, behind the same flag. `Om_tB` (line 251) needs the same treatment.
12. `src/profiles.f90` — in `init_thermodynamic_forces` (line 209) add the rotation-energy term `+ (m_i/(2 T_i)) * d/ds [Omega^2 <R^2>] * T_i/(T_i + Z T_e)` when `rotation_energy` is on, so `A1` is the gradient of the *canonical* pseudo-density; leave `A2` unchanged. Requires `dM_tds` (already available, `src/profiles.f90:184`) and `d<R^2>/ds`, obtained from the same finite difference in `s` that `neort_freq::d_Om_ds` already uses.
13. `test/test_torque.f90` (currently built but not registered, `test/CMakeLists.txt`) — add an `A1` regression against the hand-evaluated expression for `examples/base` and register it with `add_test`.

**PR 3 — validation**

14. `test/rotation_potential/` — a Python test mirroring `test/ripple_plateau/test_ripple_plateau.py`: run `neo_rt.x` on a `M_t` scan with the flag off and on, and assert the `M_t^2` scaling of the difference in `D11t`.
15. Benchmark against POTATO on the same equilibrium, using the existing `phielec_of_psi` path (`POTATO/SRC/profile_input_fixed.f90:2`); coordinate with itpplasma/NEO-RT#51 and itpplasma/rmp_torque#26. POTATO must build first — itpplasma/NEO-RT#72 blocks this step.

No `libneo` change is required for PR 1/2. If `booz_to_cyl` generalisation is instead pushed upstream, it belongs in the libneo Boozer evaluator discussed in itpplasma/libneo#305, which would make itpplasma/NEO-RT#44 a prerequisite — not recommended for a first pass.

## Acceptance criteria

- [ ] `make` succeeds for `CONFIG=Release` and `CONFIG=Debug` (the CI matrix in `.github/workflows/test.yml`).
- [ ] `make ctest` passes including the new `test_rotation_potential`.
- [ ] `make golden` passes **without regenerating** `test/golden_record/golden.h5` — proof that `rotation_energy = .false.` is a no-op.
- [ ] `make pytest` passes, including `test/ripple_plateau/test_ripple_plateau.py` (`D12/D11 = 3.0` within `RATIO_TOLERANCE = 0.08`), unchanged.
- [ ] `eta_tp(u=1)` at `s = 0.5`, `M_t = 0.36` on `examples/circ.bc` matches `1/(B0(1 + eps(1 + 2 M_eff^2)))` to 5 % relative.
- [ ] `eta_tp(u) - 1/Bmax` scales as `1/u^2` (fit exponent `-2.0 ± 0.1` over `u ∈ [1, 10]`).
- [ ] With `M_t = 0.036`, total torque in `driftorbit_torque.out` changes by < 1 % when the flag is switched on; with `M_t = 0.36`, by > 5 %.
- [ ] `rotation_energy = .true.` with an `inp_swi` that cannot supply `R(theta)` aborts with a named error, verified by a test.

## References

- F. L. Hinton and S. K. Wong, *Neoclassical ion transport in rotating axisymmetric tokamaks*, Phys. Fluids **28**, 3082 (1985) — the canonical treatment of the centrifugal potential and the rotating-frame Maxwellian in neoclassical theory.
- P. J. Catto, I. B. Bernstein and M. Tessarotto, *Ion transport in toroidally rotating tokamak plasmas*, Phys. Fluids **30**, 2784 (1987) — the strong-rotation drift-kinetic ordering that this change adopts.
- R. G. Littlejohn, *Variational principles of guiding centre motion*, J. Plasma Phys. **29**, 111 (1983) — the guiding-centre Lagrangian from which the `m v_E^2/2` term in the Hamiltonian follows; this is the same term SIMPLE#71 asks for.
- R. D. Hazeltine, *Self-consistent radial sheath*, Phys. Fluids B **1**, 2031 (1989) — origin of the orbit-squeezing factor `S = 1 - (mc/eB) d^2Phi/dpsi^2 ...`, the *finite-orbit-width* part of steep-gradient physics that is deliberately out of scope for thin-orbit NEO-RT and belongs to POTATO.
- The repo's own theory notes cite `Shaing2009-75015` and `Shaing2009-35009` (`doc/driftorbit.lyx:1970`, `:2007`) for the NTV regimes; the `v_E` dependence of the NTV resonance is the subject of that series.
- Other codes: **POTATO** (in this repo) solves the same problem with finite orbit width and a full `Phi(psi)` in the guiding-centre equations (`POTATO/SRC/velo.f90`, `POTATO/SRC/resonant_int.f90`), which is the intended cross-check. **SFINCS** (Landreman et al.) solves the drift-kinetic equation with a self-consistent `E_r` on the flux surface and is the standard reference for `E_r`-resolved neoclassical transport in non-axisymmetric geometry. **NEO-2** solves the quasilinear NTV problem in the same group (cf. itpplasma/NEO-2#100, #118). I am not confident enough about the exact citation for the sonic-rotation extension of NEO (Belli & Candy) to state a volume and year here — check before citing it in a paper.

## Scope and risk

This is not a single PR: step 11 (energy-dependent bounce frequencies) invalidates the eta-only spline architecture that `src/freq.f90` is built around and is the main risk, so PR 1 (potential + orbit dynamics + `eta` bounds, feature-flagged off) should land and be green before PR 2 touches `freq.f90`. The principal regression hazards are the golden record (`test/golden_record/golden.h5`) and the ripple-plateau analytic check, both of which must stay untouched with `rotation_energy = .false.`; a secondary hazard is OpenMP correctness, since the new potential state is per-flux-surface and must be `threadprivate` like the rest of `neort_profiles` (`src/profiles.f90:31-33`) for `test_parallel` to keep passing.
